name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ANGULAR_CLI_VERSION: 15
  GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: package.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4
        with:
          max_attempts: 2
          timeout_minutes: 2
          command: ng test --no-watch --no-progress --browsers=ChromeHeadless
      - name: Say done
        run: echo "Unit tests completed :)"

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: package.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION
      - name: Install dependencies
        run: npm install
      - name: Build and deploy to GitHub Pages
        run: |
          ng build --prod --base-href https://github.com/onedapperterm/events_calender
          npx angular-cli-ghpages --dir=dist/ --skip-install

