name: Testing
run-name: Angular Jasmine Unit Tests
on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:
env:
  ANGULAR_CLI_VERSION: 15
jobs:
  fe_test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: package.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4
        with:
          max_attempts: 2
          timeout_minutes: 5
          command: ng test
      - name: Say done
        run: echo "done :)"
